# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gdk-pixbuf
  version: 2.30.7

source:
  fn: gdk-pixbuf-2.30.7.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.30/gdk-pixbuf-2.30.7.tar.xz
  md5: 1195d26f14adfe99ff0878d37678a70a

build:
  number: 5
  detect_binary_files_with_prefix: true

requirements:
  build:
    - glib
    - gobject-introspection
    - jpeg
    - libpng
    - libtiff
    - python # needed for g-ir-scanner
    - zlib
  run:
    - glib
    - gobject-introspection
    - jpeg
    - libpng
    - libtiff
    - zlib

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: a low-level library for manipulating image data
