# Copyright 2015-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# We don't provide the rfigui right now. It needs Gtk-- > 3.0, so it wouldn't
# be a huge amount of work to make that work since we have the Gtk+ 3 stack.
# We'd need libsigc++, glibmm, and gtkmm.

{% set name = "aoflagger" %}
{% set version = "2.14.0" %}
{% set compat_version = "2.14.0" %}
{% set sha256 = "39137f2069d82eee1b6ed4028529f8a27657be36d17f722521ef304760018699" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ compat_version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - mac-cxx.patch
    - boost-python3.patch  # [py3k]

build:
  number: 1
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - boost
    - boost-cpp
    - casacore 2.4.*
    - cfitsio 3.*
    - fftw 3.3.*
    - gsl
    - hdf5
    - libxml2
    - openblas
    - python {{ python }}
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('boost-cpp') }}
    - {{ pin_compatible('cfitsio') }}
    - {{ pin_compatible('fftw') }}
    - {{ pin_compatible('openblas') }}
    - python {{ python }}

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
