# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# We don't provide the rfigui right now. It needs Gtk-- > 3.0, so it wouldn't
# be a huge amount of work to make that work since we have the Gtk+ 3 stack.
# We'd need libsigc++, glibmm, and gtkmm.

package:
  name: aoflagger
  version: "2.7.1"

source:
  fn: aoflagger-2.7.1.tar.bz2
  url: http://downloads.sourceforge.net/project/aoflagger/aoflagger-2.7.0/aoflagger-2.7.1.tar.bz2
  md5: a2f3f07ff89a3916a7eeaf3c9462a529

build:
  number: 3
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost 1.57.0 # version fix is temp hack for unavailable ICU 56
    - casa-nrao-casacore
    - cfitsio
    - cmake
    - fftw
    - gsl
    - hdf5
    - libxml2
    - openblas
  run:
    - boost 1.57.0 # version fix is temp hack for unavailable ICU 56
    - casa-nrao-casacore
    - fftw
    - gsl
    - hdf5
    - libxml2
    - openblas

about:
  home: http://aoflagger.sourceforge.net/
  license: GPLv3
  summary: automatic flagging of interference in radio astronomical data sets
