# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: pango
  version: 1.36.3

source:
  fn: pango-1.36.3.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/pango/1.36/pango-1.36.3.tar.xz
  md5: d9532826e95bdb374355deebc42441bb

build:
  number: 5

requirements:
  build:
    - cairo-gobject
    - freetype
    - glib
    - gobject-introspection
    - harfbuzz
    - python
  run:
    - cairo-gobject
    - freetype
    - glib
    - gobject-introspection
    - harfbuzz

about:
  home: http://www.gtk.org/
  license: LGPL
