# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: glib
  version: 2.46.2

source:
  fn: glib-2.46.2.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/glib/2.46/glib-2.46.2.tar.xz
  sha256: 5031722e37036719c1a09163cc6cf7c326e4c4f1f1e074b433c156862bd733db
  patches:
    - no-cocoa-notification.patch #[osx]

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - gettext #[osx]
    - libffi #[not osx]
    - python
    - zlib
  run:
    - gettext #[osx]
    - libffi #[not osx]
    - zlib

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: a low-level portability and utility library
