# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: glib
  version: 2.45.1

source:
  fn: glib-2.45.1.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/glib/2.45/glib-2.45.1.tar.xz
  md5: b2167d648db8e586758f99db5392f119

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - libffi
    - python
    - zlib
  run:
    - libffi
    - zlib

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: a low-level portability and utility library
