# NOTE: the build process embeds an absolute search path for typelib files
# (see girepository/girepository.c:init_globals()). This is bad since we want
# a relocatable binary. I think it's nontrivial to fix this here, so instead I
# work around it in pygobject3 by futzing with the environment variable
# $GI_TYPELIB_PATH.

package:
  name: gobject-introspection
  version: 1.40.0

source:
  fn: gobject-introspection-1.40.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.40/gobject-introspection-1.40.0.tar.xz
  md5: bbb103b5d88dbf2a257b7a26ae9bc666

build:
  number: 1

requirements:
  build:
    - cairo-gobject
    - glib
    - python
  run:
    - glib

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL
