# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gobject-introspection
  version: 1.44.0

source:
  fn: gobject-introspection-1.44.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.44/gobject-introspection-1.44.0.tar.xz
  md5: 7ef8a1db7f74f4193a2397b1587eb913
  patches:
    - ffi-config.patch

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cairo-gobject
    - glib
    - libffi
    - python
  run:
    - glib
    - libffi

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL
