# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: ds9
  version: "7.4"

source:
  fn: ds9.7.4.tar.gz
  url: http://ds9.si.edu/download/source/ds9.7.4.tar.gz
  sha256: e91a3aa1d8e4f5b85df0a09400b29043e2412a14c76e6712fde5942dc554433f
  patches:
    - extra-configure-args.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - modern-xorg-stack
    - libxml2
    - libxslt
    - zlib
  run:
    - modern-xorg-stack
    - libxml2
    - libxslt
    - zlib

about:
  home: http://ds9.si.edu/
  license: GPLv3+
  summary: An astronomical imaging and data visualization application.
