# Copyright 2014-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "gtk+" %}
{% set version = "3.22.30" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "a1a4a5c12703d4e1ccda28333b87ff462741dc365131fbc94c218ae81d9a6567" %}

package:
  name: gtk3  # note customization
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - m_pi.patch
    - no-module-warning.patch

build:
  number: 0
  script_env:
    - NJOBS

requirements:
  build:
    - pkg-config
    - pthread-stubs
    - python
  host:
    - xorg-xproto
    - xorg-inputproto
    - at-spi2-atk 2.26.*
    - atk 2.25.*
    - cairo {{ cairo }}
    - epoxy 1.5.*
    - fontconfig {{ fontconfig }}
    - gdk-pixbuf 2.36.*
    - glib {{ glib }}
    - gobject-introspection 1.55.*
    - pango {{ pango }}
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxi 1.7.*
    - xorg-libxrender 0.9.*
  run:
    - at-spi2-atk 2.26.*
    - atk 2.25.*
    - cairo {{ cairo }}
    - epoxy 1.5.*
    - fontconfig {{ fontconfig }}
    - gdk-pixbuf 2.36.*
    - glib {{ glib }}
    - gobject-introspection 1.55.*
    - pango {{ pango }}
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxi 1.7.*
    - xorg-libxrender 0.9.*

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: version 3 of the Gtk+ graphical toolkit
