# Copyright 2016-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "adwaita-icon-theme" %}
{% set version = "3.26.1" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "28ba7392c7761996efd780779167ea6c940eedfb1bf37cfe9bccb7021f54d79d" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script_env:
    - NJOBS

requirements:
  build:
    - gtk3
    - librsvg  # for SVG loading
    - pkg-config
  run:

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: graphics resources for the Adwaita Gtk+ theme
