# Copyright 2016-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Anaconda has moved on to Qt5, but CASA requires Qt4. We can't just rely on
# the existing Anaconda Qt4 package, though, because since it was last built
# the conda build system was changed to use longer paths, so we can't build
# new packages that depend on the old version. Fun times. We also include
# DBus support on OS X, which is not included in the stock version, likely
# because dbus-cxx is totally busted.
#
# el-capitan.patch is from
# https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb

package:
  name: qt4
  version: 4.8.7

source:
  fn: qt-everywhere-opensource-src-4.8.7.tar.gz
  url: http://download.qt-project.org/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.tar.gz
  md5: d990ee66bf7ab0c785589776f35ba6ad
  patches:
    - acceptance.patch
    - qmake-arch.patch  # [osx]
    - long-paths.patch
    - el-capitan.patch  # [osx]

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - dbus-cxx 0.9.*
    - fontconfig 2.12.*  # [linux]
    - freeglut 3.0.*  # [linux]
    - freetype 2.7|2.7.*  # [linux]
    - jpeg 9*
    - libpng >=1.6.28,<1.7
    - libtiff 4.0.*
    - libxml2 2.9.*
    - libuuid 1.0.*  # [linux]
    - openssl 1.0.*
    - pango 1.40.*  # [linux]
    - python
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3.*
    - xorg-xextproto
    - xorg-xproto
    - zlib 1.2.*

  run:
    - dbus-cxx 0.9.*
    - fontconfig 2.12.*  # [linux]
    - freeglut 3.0.*  # [linux]
    - freetype 2.7|2.7.*  # [linux]
    - jpeg 9*
    - libpng >=1.6.28,<1.7
    - libtiff 4.0.*
    - libxml2 2.9.*
    - libuuid 1.0.*  # [linux]
    - openssl 1.0.*
    - pango 1.40.*  # [linux]
    - xorg-libx11 1.6.*
    - xorg-libxext 1.3.*
    - zlib 1.2.*

about:
    home: http://qt-project.org
    license: LGPL
    summary: 'Version 4 of the Qt framework, modified to be parallel-installable with Qt5.'
