# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `cmake-fixes.patch`.
# Build on CentOS 5.

package:
  name: casa-asap
  version: "4.5"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_5/
  svn_rev: 35147
  svn_ignore_externals: yes
  patches:
    - cmake-fixes.patch

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - atlas
    - boost
    - casa-nrao-casacore
    - casa-tools
    - cfitsio
    - cmake
    - libxml2
    - pgplot
    - rpfits
    - wcslib
  run:
    - boost
    - casa-nrao-casacore
    - casa-tools
    - cfitsio
    - libxml2
    - pgplot
    - wcslib

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: single-dish radio telescope analysis package for CASA
