# Copyright 2015-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "grip" %}
{% set version = "4.5.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 048b7e5c738ed80bee345bd10840f27eb31687eb67132b40f2473dc1cf67aa0f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - grip = grip:main

requirements:
  host:
    - pip
    - python
  run:
    - docopt >=0.6.2
    - flask >=0.10.1
    - markdown >=2.5.1
    - path-and-address >=1.0.0
    - pygments >=1.6
    - requests >=2.4.1

test:
  imports:
    - grip

  commands:
    - grip --help

about:
  home: http://github.com/joeyespo/grip
  license: MIT
  # the files distributed on PyPI do not include LICENSE
  summary: 'Render local readme files before sending off to GitHub.'
