# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Stolen from github:conda/conda-recipes, which in turn credits "jeanconn" at
# https://binstar.org/jeanconn/fftw

package:
    name: fftw
    version: "3.3.4"

source:
    fn: fftw-3.3.4.tar.gz
    url: http://www.fftw.org/fftw-3.3.4.tar.gz
    md5: 2edab8c06b24feeb3b82bbb3ebf3e7b3

build:
  number: 3
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
    build:

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: http://fftw.org
    license: GNU General Public License (GPL)
    summary: The fastest Fourier transform in the west.
