# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# This package should only be provided on OS X, which doesn't have GNU Gettext
# type support built in.

package:
  name: gettext
  version: 0.19.6

source:
  fn: gettext-0.19.6.tar.xz
  url: http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.6.tar.xz
  sha256: 9b95816620fd1168cb4eeca0e9dc0ffd86e864fc668f76f5e37cc054d6982e51

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - dont-build-me-on-linux #[not osx]

about:
  home: https://www.gnu.org/software/gettext/
  license: GPLv3
  summary: Tools for writing multilingual software.
