# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Shortcut to get new MD5 sum:
#
#   curl -s https://pypi.python.org/pypi/pwkit/ |grep md5= |grep -v linux |sed -e 's/.*md5=//'

package:
  name: pwkit
  version: "0.8.3"

source:
  fn: pwkit-0.8.3.tar.gz
  url: https://pypi.python.org/packages/52/6e/3df3935ddbdd17b3c000e885b00d322b7e374c45309e10d87b6cc4703c80/pwkit-0.8.3.tar.gz
  md5: 84a0540e709c801f0123dd422bfb52c3

build:
  number: 0
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - latexdriver = pwkit.cli.latexdriver:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline

requirements:
  build:
    - numpy
    - pathlib # [py2k]
    - python
    - setuptools
    - six

  run:
    - numpy
    - pathlib # [py2k]
    - python
    - six

test:
  imports:
    - pwkit

about:
  home: https://github.com/pkgw/pwkit/
  license: MIT License
  summary: Miscellaneous scientific and astronomical tools
