# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Shortcut to get new MD5 sum:
#
#   curl -s https://pypi.python.org/pypi/pwkit/ |grep md5= |grep -v linux |sed -e 's/.*md5=//'

package:
  name: pwkit
  version: "0.6.0"

source:
  fn: pwkit-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pwkit/pwkit-0.6.0.tar.gz
  md5: 89a9baf719be284a7169cec952e3451a

build:
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - latexdriver = pwkit.cli.latexdriver:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline

  # build number if rebuilding same version:
  # number: 1

requirements:
  build:
    - numpy
    - pathlib # [py2k]
    - python
    - setuptools
    - six

  run:
    - numpy
    - pathlib # [py2k]
    - python
    - six

test:
  imports:
    - pwkit

  #commands:
    # (commands)

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  #requires:
    #- nose # e.g.

about:
  home: https://github.com/pkgw/pwkit/
  license: MIT License
  summary: Miscellaneous scientific and astronomical tools
