# Copyright 2014-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Shortcut to get new SHA256 digest:
#
#   curl -s https://pypi.python.org/pypi/pwkit/ |grep sha256-link |tail -n1

{% set name = "pwkit" %}
{% set version = "0.8.7" %}
{% set sha256 = "c5e336032cbd45b73331834f6af2e6f916e25c48ab4d3c767c26fc3f9362471f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=files.txt
  entry_points:
    - astrotool = pwkit.cli.astrotool:commandline
    - casatask = pwkit.environments.casa.tasks:commandline
    - imtool = pwkit.cli.imtool:commandline
    - latexdriver = pwkit.cli.latexdriver:commandline
    - pkcasascript = pwkit.environments.casa.scripting:commandline
    - pkenvtool = pwkit.environments:commandline
    - wrapout = pwkit.cli.wrapout:commandline

requirements:
  build:
    - numpy
    - pathlib # [py2k]
    - python
    - setuptools
    - six

  run:
    - numpy
    - pathlib # [py2k]
    - python
    - six

test:
  imports:
    - pwkit

about:
  home: https://github.com/pkgw/pwkit/
  license: MIT License
  summary: Miscellaneous scientific and astronomical tools.
