package:
  name: cairo-gobject
  version: 1.12.18

source:
  fn: cairo-1.12.18.tar.xz
  url: http://cairographics.org/releases/cairo-1.12.18.tar.xz
  sha1: a76940b58da9c83b8934264617135326c0918f9d
  patches:
    - hack-features.patch

build:
  number: 1

requirements:
  build:
    - freetype
    - glib
    - libpng
    - pixman
    - zlib
  run:
    - cairo

about:
  home: http://cairographics.org/
  license: LGPL 2.1 and MPL 1.1
