# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "pycairo" %}
{% set version = "1.11.0" %}
{% set sha256 = "b95fe7192e3f50be651dd20abc21ad51f8d47dbf02b8ac6603b6b3d06b0a7dd8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pygobject/pycairo/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cairo 1.14.*
    - python
    - xorg-libx11 1.6.*
    - xorg-xproto
  run:
    - cairo 1.14.*
    - python

test:
  imports:
    - cairo
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1, MPL 1.1
  summary: 'Python bindings for the Cairo graphics library.'

extra:
  recipe-maintainers:
    - pkgw
