# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: pycairo
  version: 1.10.0

source:
  fn: py2cairo-1.10.0.tar.bz2  # [py2k]
  url: http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2  # [py2k]
  md5: 20337132c4ab06c1146ad384d55372c5  # [py2k]
  fn: pycairo-1.10.0.tar.bz2  # [not py2k]
  url: http://cairographics.org/releases/pycairo-1.10.0.tar.bz2  # [not py2k]
  md5: e6fd3f2f1e6a72e0db0868c4985669c5  # [not py2k]
  patches:
    # Note that there are other patches that are applied through build.sh
    # since the waf-based build system is SUPER ANNOYING.
    #
    # The "region" patch does not actually work! I'm having trouble figuring
    # out why and there's only so much time I want to spend on this right now.
    - 101_pycairo-region-common.patch
    - 101_pycairo-region-py2k.patch  # [py2k]
    - 101_pycairo-region-py3k.patch  # [not py2k]
    - 102_initfix.patch  # [py2k]

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cairo 1.14.*
    - python
    - xorg-libx11 1.6.*
    - xorg-xproto
  run:
    - cairo 1.14.*
    - python

test:
  imports:
    - cairo
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://cairographics.org/pycairo/
  license: LGPL 2.1, MPL 1.1
  summary: 'Python bindings for the Cairo graphics library.'
