# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: texlive-core
  version: "20150521"

source:
  fn: texlive-20150521-source.tar.xz
  url: http://mirrors.ctan.org/systems/texlive/Source/texlive-20150521-source.tar.xz
  sha256: ed9bcd7bdce899c3c27c16a8c5c3017c4f09e1d7fd097038351b72497e9d4669

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cairo #[not osx]
    - freetype
    - gmp
    - icu
    - libpng
    - modern-xorg-stack
    - mpfr
    - pixman
    - zlib
  run:
    - cairo #[not osx]
    - freetype
    - gmp
    - icu
    - libpng
    - modern-xorg-stack
    - mpfr
    - pixman
    - zlib

about:
  home: https://www.tug.org/texlive/
  license: LPPL
  summary: Core binaries of the TeXLive distribution.
