# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: xerces-c28
  version: "2.8.0"

source:
  # Apache folks really discourage people from using xerces 2.x, but
  # I found a mirror that still has it.
  fn: openlogic-xerces-c-2.8.0-all-src-1.zip
  url: https://olex-secure.openlogic.com/content/openlogic/xerces-c/2.8.0/openlogic-xerces-c-2.8.0-all-src-1.zip
  md5: 6eebe4fda688e78eaeb513cb964cda8c

build:
  number: 0

requirements:
  build:

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache version 2.0
  summary: an XML parsing framework
