# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: texlive-selected
  version: "20160222"

source:
  fn: texlive-selected-20160222.tar.bz2
  url: http://newton.cx/~peter/files/texlive-selected-20160222.tar.bz2
  sha256: d4373f9c2028860acaa38696b3b6ee44ed24cee9683d00415fcf342e7297a4fe

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - texlive-core
  run:
    - texlive-core

about:
  home: https://www.tug.org/texlive/
  license: LPPL
  summary: Selected TeXLive packages needed for compiling scientific documents.
