# Copyright 2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: texlive-selected
  version: "20160215"

source:
  fn: texlive-selected-20160215.tar.bz2
  url: http://newton.cx/~peter/files/texlive-selected-20160215.tar.bz2
  sha256: f25de92ad6f365e1415c56ae342b22d698b52b23015d0c1934873dd890b29d6b

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - texlive-core
  run:
    - texlive-core

about:
  home: https://www.tug.org/texlive/
  license: LPPL
  summary: Selected TeXLive packages needed for compiling scientific documents.
