{% set name = "tectonic" %}
{% set version = "0.1.0" %}
{% set sha256 = "ea0f925ea211426bbbe4631d16f4fd1e3fd7fb293cacf809a5dde0065a7a64a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: download.tar.gz
  url: https://crates.io/api/v1/crates/{{ name }}/{{ version }}/download
  sha256: {{ sha256 }}
  patches:
    - byte.patch

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - rust-toolchain
    - cargo
    - fontconfig 2.12.*  # [not osx]
    - freetype 2.7|2.7.*
    - graphite2 1.3.*
    - harfbuzz 1.4.*
    - icu 58.*
    - libpng >=1.6.28,<1.7
    - poppler 0.52.*
    - zlib 1.2.*
  run:
    - fontconfig 2.12.*  # [not osx]
    - freetype 2.7|2.7.*
    - graphite2 1.3.*
    - harfbuzz 1.4.*
    - icu 58.*
    - libpng >=1.6.28,<1.7
    - poppler 0.52.*
    - zlib 1.2.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/pkgw/tectonic/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A modernized, complete, standalone TeX/LaTeX engine.'

extra:
  recipe-maintainers:
    - pkgw
