# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gsl
  version: "1.16"

source:
  fn: gsl-1.16.tar.gz
  url: http://ftpmirror.gnu.org/gsl/gsl-1.16.tar.gz
  md5: e49a664db13d81c968415cd53f62bc8b

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - openblas

about:
  home: http://www.gnu.org/software/gsl/gsl.html
  license: GPL
  summary: the GNU Scientific Library
