# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gsl
  version: "2.2.1"

source:
  fn: gsl-2.2.1.tar.gz
  url: http://ftpmirror.gnu.org/gsl/gsl-2.2.1.tar.gz
  md5: 3d90650b7cfe0a6f4b29c2d7b0f86458

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:

about:
  home: http://www.gnu.org/software/gsl/gsl.html
  license: GPL
  summary: the GNU Scientific Library
