# Copyright 2017-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "wsclean" %}
{% set version = "2.5" %}
{% set sha256 = "d9834db9bb77d99d82b90526d6b904bfcd25db19037e24ae6c053b5b8d7ff621" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - osx.patch  # [osx]

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cmake
    - boost 1.66.0
    - casacore 2.4.*
    - fftw 3.3.*
    - gsl 2.2.*
  run:
    - boost 1.66.0
    - casacore 2.4.*
    - fftw 3.3.*
    - gsl 2.2.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - wsclean -version

about:
  home: http://wsclean.sourceforge.net/
  license: GPLv3
  summary: fast, widefield interferometric imaging
