# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: casa-data
  version: r10774

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa-data/distro/
  svn_rev: 10774
  svn_ignore_externals: yes

build:
  number: 0

requirements:
  build:

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: supporting data files for CASA
