package:
  name: harfbuzz
  version: 1.0.6

source:
  fn: harfbuzz-1.0.6.tar.bz2
  url: http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.0.6.tar.bz2
  sha256: f616a7fbdc78a627043f9029000bf08c0c71df59cde4143fc92a014f6a993b26

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - freetype
    - glib
    - gobject-introspection
  run:
    - freetype
    - glib
    - gobject-introspection

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  summary: An OpenType text shaping engine.
