# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gtk3
  version: 3.12.0

source:
  fn: gtk+-3.12.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gtk+/3.12/gtk+-3.12.0.tar.xz
  md5: 4e493fb68cded7420a7d8bcebdf13811
  patches:
    - m_pi.patch

build:
  number: 3

requirements:
  build:
    - at-spi2-atk
    - atk
    - cairo-gobject
    - gdk-pixbuf
    - glib
    - gobject-introspection
    - pango
    - python
  run:
    - at-spi2-atk
    - atk
    - gdk-pixbuf
    - glib
    - gobject-introspection
    - pango

about:
  home: http://www.gtk.org/
  license: LGPL
