# Copyright 2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "epoxy" %}
{% set version = "1.5.2" %}
{% set sha256 = "a9562386519eb3fd7f03209f279f697a8cba520d3c155d6e253c3e138beca7d8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anholt/libepoxy/releases/download/{{ version }}/libepoxy-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_compatible('epoxy', max_pin='x.x') }}

requirements:
  build:
    - pkg-config
    - pthread-stubs
    - python
    - xorg-util-macros
    - {{ compiler('c') }}
  host:
    - xorg-xproto
    - xorg-libx11 1.6.*
  run:
    - xorg-libx11 1.6.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/anholt/libepoxy
  license: MIT
  license_file: COPYING
  summary: 'A library for handling OpenGL function pointer management for you.'
