package:
  name: omegaplot
  version: !!str 0.3

source:
  fn: omegaplot-0.3.tar.bz2
  url: https://pypi.python.org/packages/source/o/omegaplot/omegaplot-0.3.tar.gz
  md5: d936922773ddccc3134fef3f73e10a68

build:
  number: 0
  entry_points:
    - omegafig = oputil.omegafig:cmdline
    - omegamap = oputil.omegamap:cmdline

requirements:
  build:
    - numpy
    - py2cairo
    - python
    - setuptools
  run:
    - numpy
    - py2cairo
    - python

about:
  home: http://newton.cx/~peter/
  license: GPL
