# Copyright 2014-2018 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "omegaplot" %}
{% set version = "0.7.4" %}
{% set sha256 = "9a6604f6da09fead151505c2303580e0b2b0e6a4ec627a050232c3703ce6f600" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=files.txt
  entry_points:
    - omegafig = oputil.omegafig:cmdline
    - omegamap = oputil.omegamap:cmdline

requirements:
  build:
    - nomkl
    - numpy
    - pycairo
    - python
    - setuptools
    - six
  run:
    - numpy
    - pycairo
    - python
    - six

test:
  imports:
    - omega
    - oputil

about:
  home: https://newton.cx/~peter/
  license: GPL
  summary: A better-than-publication-quality plotting library based on Cairo.
