# Copyright 2014-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Shortcut to get new filename and MD5 sum:
#
#   curl -s https://pypi.python.org/pypi/omegaplot/ |grep md5= |grep -v linux

package:
  name: omegaplot
  version: "0.7.1"

source:
  fn: omegaplot-0.7.1.tar.gz
  url: https://pypi.python.org/packages/93/71/27a7a6097b43586c44f8d3d869f76e8ba8245ce2f730c3594023865efd5f/omegaplot-0.7.1.tar.gz
  md5: 275f4ff352dfbb7d58e461f9a3802767

build:
  number: 0
  entry_points:
    - omegafig = oputil.omegafig:cmdline
    - omegamap = oputil.omegamap:cmdline

requirements:
  build:
    - nomkl
    - numpy
    - py2cairo # [py2k]
    - py3cairo # [py3k]
    - python
    - setuptools
    - six
  run:
    - numpy
    - py2cairo # [py2k]
    - py3cairo # [py3k]
    - python
    - six

about:
  home: http://newton.cx/~peter/
  license: GPL
  summary: A better-than-publication-quality plotting library based on Cairo.
