# Copyright 2015-2016 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# This is an alternate version of "libffi", needed on both OS X and Linux.
# Anaconda's Linux package includes a busted .la file and no pkg-config file.
# OS X includes a very old version of libffi.

package:
  name: libffi32
  version: "3.2.1"

source:
  fn: libffi-3.2.1.tar.gz
  url: ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
  sha1: 280c265b789e041c02e5c97815793dfc283fb1e6
  patches:
    - rename-lib.patch

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:

about:
  home: https://sourceware.org/libffi/
  license: MIT
  summary: A portable foreign function interface library
