package:
  name: pathlib
  version: "1.0.1"

source:
  fn: pathlib-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pathlib/pathlib-1.0.1.tar.gz
  md5: 5099ed48be9b1ee29b31c82819240537

build:
  number: 0

requirements:
  build:
    - python <3.4
  run:
    - python <3.4

about:
  home: https://pathlib.readthedocs.org/
  license: MIT License
  summary: 'Object-oriented filesystem paths'
