# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# This package is merged into the main distribution in Python >= 3.4.

package:
  name: pathlib
  version: "1.0.1"

source:
  fn: pathlib-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pathlib/pathlib-1.0.1.tar.gz
  md5: 5099ed48be9b1ee29b31c82819240537

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://pathlib.readthedocs.org/
  license: MIT License
  summary: Object-oriented filesystem paths
