# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.

package:
  name: casa-nrao-casacore
  version: "4.6.0"

source:
  # FIXME: this server currently (2015/12) has a bad SSL certificate, breaking
  # the checkout! It can be worked around if you manually approve the cert.
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - default-root.patch
    - ncursesw.patch

build:
  number: 5
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - cfitsio 3.410
    - cmake
    - fftw 3.3.*
    - hdf5 1.8.17|1.8.17.*
    - ncurses 5.9*
    - nomkl # speeds up by avoiding big download
    - numpy
    - openblas 0.2.19|0.2.19.*
    - readline 6.2*
    - wcslib 5.15
  run:
    - cfitsio 3.410
    - fftw 3.3.*
    - hdf5 1.8.17|1.8.17.*
    - libgfortran 3.0.0 #[linux]
    - ncurses 5.9*
    - numpy
    - openblas 0.2.19|0.2.19.*
    - readline 6.2*
    - wcslib 5.15

about:
  home: http://casa.nrao.edu/
  license: GPL version 2
  summary: core libraries for CASA
