# Copyright 2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.
# Build on CentOS 5.

package:
  name: casa-tools
  version: "4.6.0"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - casaroot.patch
    - no-java.patch
    - mydbus.patch #[osx]

build:
  number: 0
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost 1.57.0 # version fix is temp hack for unavailable ICU 56
    - casa-nrao-casacore
    - cmake
    - dbus-cxx
    - dbus-client
    - fftw
    - gsl
    - libgfortran 3.0 #[linux]
    - libsakura 2.0.0
    - libxml2
    - libxslt
    - nomkl # speeds by avoiding big download
    - openblas #[not osx]
    - pgplot
    - readline
    - rpfits
    - qt
    - qt-dbus-component #[osx]
    - qwt5
    - xerces-c28
  run:
    - boost 1.57.0 # version fix is temp hack for unavailable ICU 56
    - casa-nrao-casacore
    - dbus-cxx
    - dbus-client
    - fftw
    - gsl
    - libgfortran 3.0 #[linux]
    - libsakura
    - libxml2
    - libxslt
    - openblas #[not osx]
    - pgplot
    - readline
    - qt
    - qt-dbus-component #[osx]
    - qwt5
    - xerces-c28

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  summary: scientific tool implementations for CASA
