# Copyright 2015-2017 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.
#
# NOTE: if updating major or minor version, update `so-versioning.patch`.
# Build on CentOS 5.

package:
  name: casa-tools
  version: "4.6.0"

source:
  svn_url: https://svn.cv.nrao.edu/svn/casa/branches/release-4_6/
  svn_rev: 36590
  svn_ignore_externals: yes
  patches:
    - so-versioning.patch
    - casaroot.patch
    - no-java.patch
    - mydbus.patch
    - ncursesw.patch

build:
  number: 6
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - boost 1.63.0
    - casa-nrao-casacore 4.6.*
    - cmake
    - dbus-cxx 0.9.*
    - dbus 1.10.*
    - fftw 3.3.*
    - gsl 2.2.*
    - libgfortran 3.0.0  # [linux]
    - libsakura 2.0.0
    - libxml2 2.9.*
    - libxslt 1.1.*
    - ncurses 5.9*
    - nomkl # speeds by avoiding big download
    - openblas 0.2.*
    - pgplot 5.2.*
    - readline 6.*
    - rpfits 2.*
    - qt4 4.8.*
    - qwt5 5.2.*
    - xerces-c28
  run:
    - boost 1.63.0
    - casa-nrao-casacore 4.6.*
    - dbus-cxx 0.9.*
    - dbus 1.10.*
    - fftw 3.3.*
    - gsl 2.2.*
    - libgfortran 3.0.0  # [linux]
    - libsakura 2.0.0
    - libxml2 2.9.*
    - libxslt 1.1.*
    - ncurses 5.9*
    - openblas 0.2.*
    - pgplot 5.2.*
    - readline 6.*
    - rpfits 2.*
    - qt4 4.8.*
    - qwt5 5.2.*
    - xerces-c28

about:
  home: http://casa.nrao.edu/
  license: GPLv2
  summary: scientific tool implementations for CASA
